spring:
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  data:
    redis:
      host: ${REDIS_HOSTNAME}
      port: ${REDIS_PORT}

#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 200MB
#      max-request-size: 300MB

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AMAZON_S3_ACCESS_KEY}
      secret-key: ${AMAZON_S3_SECRET_KEY}


jwt:
  secret: ${JWT_SECRET_KEY}

coolSms:
  api:
    sender: ${SMS_SENDER}
    key: ${SMS_KEY}
    secretKey: ${SMS_SECRET_KEY}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


firebase:
  project-URL: ${FCM_PROJECT_URL}
  key:
    type: service_account
    project_id: ${FCM_PROJECT_ID}
    private_key_id: ${FCM_PRIVATE_KEY_ID}
    private_key: ${FCM_PRIVATE_KEY}
    client_email: ${FCM_CLIENT_EMAIL}
    client_id: ${FCM_CLIENT_ID}
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: ${FCM_CLIENT_X509_CERT_URL}
    universe_domain: googleapis.com

gpt:
  model: gpt-3.5-turbo
  api:
    key: ${GPT_KEY}
    url: ${GPT_URL}

security:
  oauth2:
    client:
      registration:
        kakao:
          client_id: ${KAKAO_REST_API_KEY}
          redirect_uri: ${KAKAO_REDIRECT_URI}

management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: always